import type { ContainerShipment, CustomerInvoice, ErpProduct, ProductMapping, QboProduct } from "@/lib/inventory-core";

export const erpProducts: ErpProduct[] = [
  { id: "p1", sku: "OE-ALPHA-001", name: "Olympic Bench Pro", onFloorQty: 5 },
  { id: "p2", sku: "OE-RACK-110", name: "Titan Power Rack", onFloorQty: 12 },
  { id: "p3", sku: "OE-PLATE-045", name: "Steel Plate Set 45lb", onFloorQty: 30 },
  { id: "p4", sku: "OE-BAR-700", name: "Competition Barbell", onFloorQty: 8 },
];

export const qboProducts: QboProduct[] = [
  { id: "q1", name: "Bench-Professional" },
  { id: "q2", name: "Power Rack (Heavy Duty)" },
  { id: "q3", name: "Steel Plates 45" },
  { id: "q4", name: "Comp Bar - Black Zinc" },
  { id: "q5", name: "Bench Pro Bundle" },
];

export const productMappings: ProductMapping[] = [
  { qboProductId: "q1", erpProductId: "p1", mappedAt: "2026-06-10" },
  { qboProductId: "q2", erpProductId: "p2", mappedAt: "2026-06-10" },
  { qboProductId: "q3", erpProductId: "p3", mappedAt: "2026-06-11" },
  { qboProductId: "q4", erpProductId: "p4", mappedAt: "2026-06-11" },
];

export const customerInvoices: CustomerInvoice[] = [
  {
    id: "inv1",
    invoiceNo: "INV-22118",
    customerName: "Northline Athletics",
    paymentStatus: "Paid",
    createdAt: "2026-06-28",
    approvedByShipping: true,
    lines: [
      { erpProductId: "p1", qty: 6 },
      { erpProductId: "p4", qty: 2 },
    ],
  },
  {
    id: "inv2",
    invoiceNo: "INV-22119",
    customerName: "Peak Fitness Supply",
    paymentStatus: "Partially Paid",
    createdAt: "2026-06-29",
    approvedByShipping: false,
    lines: [{ erpProductId: "p1", qty: 4 }],
  },
  {
    id: "inv3",
    invoiceNo: "INV-22120",
    customerName: "Grit Gym Group",
    paymentStatus: "Partially Paid",
    createdAt: "2026-06-29",
    approvedByShipping: false,
    lines: [{ erpProductId: "p2", qty: 3 }],
  },
  {
    id: "inv4",
    invoiceNo: "INV-22121",
    customerName: "Iron Harbor",
    paymentStatus: "Unpaid",
    createdAt: "2026-06-30",
    approvedByShipping: false,
    lines: [{ erpProductId: "p3", qty: 5 }],
  },
];

export const containerShipments: ContainerShipment[] = [
  {
    id: "c226",
    poNumber: "226",
    containerNo: "ONEU1971795",
    supplier: "Hiker",
    trackingNumber: "ONEU1971795",
    trackingSource: "OEC",
    origin: "Qingdao, Shandong, CN",
    originPortDate: "2026-05-24",
    onShipDate: "2026-05-28",
    poDate: "2026-03-10",
    portDate: "2026-08-20",
    portName: "Long Beach",
    paymentStatus: "Paid",
    status: "On the ship",
    inventoryStatus: "On Order",
    uploadedAt: "2026-03-10",
    trackingConnected: true,
    milestones: [
      { stage: "At origin port", date: "2026-05-24" },
      { stage: "On the ship", date: "2026-05-28" },
    ],
    items: [
      { erpProductId: "p1", qty: 30 },
      { erpProductId: "p2", qty: 30 },
    ],
  },
  {
    id: "c2",
    poNumber: "229",
    containerNo: "MSCU1102933",
    supplier: "Titan Forge",
    trackingNumber: "MSCU1102933",
    trackingSource: "Maersk",
    origin: "Ningbo, Zhejiang, CN",
    originPortDate: "2026-06-22",
    onShipDate: "2026-06-26",
    poDate: "2026-04-21",
    portDate: "2026-09-04",
    portName: "Savannah",
    paymentStatus: "Partially Paid",
    status: "At origin port",
    inventoryStatus: "On Order",
    uploadedAt: "2026-04-21",
    trackingConnected: true,
    milestones: [{ stage: "At origin port", date: "2026-06-22" }],
    items: [
      { erpProductId: "p3", qty: 80 },
      { erpProductId: "p4", qty: 24 },
    ],
  },
  {
    id: "c3",
    poNumber: "214",
    containerNo: "OOLU7649201",
    supplier: "Hiker",
    trackingNumber: "OOLU7649201",
    trackingSource: "OEC",
    origin: "Xiamen, Fujian, CN",
    originPortDate: "2026-02-15",
    onShipDate: "2026-02-19",
    poDate: "2026-01-05",
    portDate: "2026-04-24",
    portName: "Long Beach",
    paymentStatus: "Paid",
    status: "Received into inventory",
    inventoryStatus: "Received",
    uploadedAt: "2026-01-05",
    trackingConnected: false,
    milestones: [
      { stage: "At origin port", date: "2026-02-15" },
      { stage: "On the ship", date: "2026-02-19" },
      { stage: "At destination port", date: "2026-04-24" },
      { stage: "Released from port", date: "2026-04-27" },
      { stage: "Arrived at warehouse", date: "2026-04-30" },
      { stage: "Received into inventory", date: "2026-05-01" },
    ],
    items: [
      { erpProductId: "p1", qty: 12 },
      { erpProductId: "p4", qty: 10 },
    ],
  },
];
